{
 "title": "IB Metrics Dashboard",
 "description": "This dashboard displays metrics collected by ib-metrics-pyclient",
 "tags": [ "ib-metrics-pyclient" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "brokername",
    "label": "Broker",
    "query": "label_values(ib_broker_status, brokername) \t"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(ib_broker_status{brokername=~\"$brokername\"}, instance) "
   },
   {
    "name": "egname",
    "label": "Execution Group",
    "query": "label_values(ib_exec_group_status{brokername=~\"$brokername\", instance=~\"$instance\"}, egname)"
   },
   {
    "name": "appname",
    "label": "Application",
    "query": "label_values(ib_application_status{brokername=~\"$brokername\" ,instance=~\"$instance\", egname=~\"$egname\"}, appname)"
   },
   {
    "name": "messageflowname",
    "label": "Message Flow",
    "query": "label_values(ib_message_flow_status{brokername=~\"$brokername\", instance=~\"$instance\", egname=~\"$egname\", appname=~\"$appname\"}, messageflowname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Brokers Status",
   "type": "table",
   "description": "The panel shows the ib_broker_status metric.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ib_broker_status{brokername=~\"$brokername\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Execution Groups Status",
   "type": "table",
   "description": "The panel shows the ib_exec_group_status metric.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ib_exec_group_status{brokername=~\"$brokername\", instance=~\"$instance\", egname=~\"$egname\"}"
    }
   ]
  },
  {
   "title": "Applications Status",
   "type": "table",
   "description": "The panel shows the ib_application_status metric.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ib_application_status{brokername=~\"$brokername\",instance=~\"$instance\", egname=~\"$egname\", appname=~\"$appname\"}"
    }
   ]
  },
  {
   "title": "Message flows Status",
   "type": "table",
   "description": "The panel shows the ib_message_flow_status metric.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ib_message_flow_status{brokername=~\"$brokername\", instance=~\"$instance\", egname=~\"$egname\", appname=~\"$appname\", messageflowname=~\"$messageflowname\"}"
    }
   ]
  }
 ]
}